from github import Github
from datetime import datetime
from datetime import date
import subprocess
import config


def create_manifest(branch):
    commands = "git checkout -b {0}; brew list > {1}; git push origin {0}".format(
        branch, config.MYBREWFILE)

    # commands = "git checkout -b {0}; date > {1}; git commit -m 'auto' {1}; git push origin {0}".format(
    #     branch, config.MYBREWFILE)

    process = subprocess.Popen(
        commands, shell=True, stdout=subprocess.PIPE, stdin=subprocess.PIPE)
    out = process.communicate()
    print(out)


def open_pullrequest(branch):
    g = Github(config.GH_ACCESS_TOKEN)
    repo = g.get_repo('aniv/mybrew')
    pr = repo.create_pull(title="App list update for {0}".format(date.today().strftime("%B %d, %Y")),
                          body='Auto-generated by mybrew',
                          head=branch,
                          base="master")


def main():
    branch = 'nb-{0}'.format(datetime.now().strftime("%H%M%S"))
    create_manifest(branch)
    open_pullrequest(branch)


if __name__ == '__main__':
    main()
